# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_kind', models.CharField(choices=[('CPU', 'CPU'), ('BRD', 'Board'), ('RAM', 'RAM'), ('VGA', 'VGA'), ('POW', 'Power'), ('HDD', 'HDD'), ('SSD', 'SSD'), ('ODD', 'ODD')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('option', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='custom',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='hdd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdd', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='odd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odd', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='ssd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssd', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='custom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custom',
            name='vga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vga', to='custom.Hardware'),
        ),
        migrations.AddField(
            model_name='compa',
            name='hardware',
            field=models.ManyToManyField(to='custom.Hardware'),
        ),
    ]
