# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='title',
            field=models.CharField(default='text', max_length=50),
            preserve_default=False,
        ),
    ]
