# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
