# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20180410_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='title',
        ),
    ]
