# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180507_1438'),
        ('custom', '0002_auto_20180423_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_comments', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_comments', to='custom.Custom'),
        ),
    ]
