# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_auto_20180413_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='hardware',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
