# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_remove_hardware_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
