# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_remove_hardware_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('craete_date', models.DateTimeField(auto_now_add=True)),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Custom')),
            ],
        ),
    ]
