# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='craete_date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='custom.Custom'),
        ),
    ]
