# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 07:42
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0010_auto_20180417_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='hard_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='custom/hardware'),
        ),
    ]
