# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-17 08:36
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_hardware_hard_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hard_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='hardware'),
        ),
    ]
