# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-27 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180427_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardcomment',
            old_name='custom',
            new_name='board',
        ),
    ]
