# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180427_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='boardcomment',
            name='board',
        ),
        migrations.DeleteModel(
            name='BoardComment',
        ),
    ]
